# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hazmatcpp <- function(par, d, detectfn) {
    .Call(`_secrdesign_hazmatcpp`, par, d, detectfn)
}

Lambdacpp <- function(type, par, d, detectfn) {
    .Call(`_secrdesign_Lambdacpp`, type, par, d, detectfn)
}

Qpmcpp <- function(par, D, d, detectfn, noccasions) {
    .Call(`_secrdesign_Qpmcpp`, par, D, d, detectfn, noccasions)
}

En2cpp <- function(type, par, D, d, detectfn, noccasions) {
    .Call(`_secrdesign_En2cpp`, type, par, D, d, detectfn, noccasions)
}

